// The Mermaid the state-diagram board exports as (V1-PLAN §3, §9 D5's state half).
//
// Written by hand from the drawing (fixtures/state.ts), not generated by the
// exporter: this is what `toMermaid` must say, and the one text every hand of
// the board must export. The ids are the marks' own, said in Mermaid as D2
// says them: a state is its box's stroke (`stroke_1`). The flows run across
// the page, so it says `direction LR`. States come in reading order — the
// drawing's columns, left to right, Running above Paused — then the
// transitions by the states they leave and arrive at, in that order; the
// initial dot and the final ring are both `[*]`, which Mermaid reads as the
// start where a transition leaves it and as the end where one arrives.
//
// A state is `state "<name>" as <id>`; a transition is `<from> --> <to>: <words>`,
// a self-transition from a state to itself, a transition with no writing no
// colon. Writing nobody has read is written "(unread writing)".

/** The board before anybody has read the writing. */
export const STATE_MERMAID_UNREAD = `stateDiagram-v2
    direction LR
    state "(unread writing)" as stroke_1
    state "(unread writing)" as stroke_2
    state "(unread writing)" as stroke_3
    [*] --> stroke_1
    stroke_1 --> stroke_2: (unread writing)
    stroke_2 --> stroke_2: (unread writing)
    stroke_2 --> stroke_3: (unread writing)
    stroke_2 --> [*]: (unread writing)
    stroke_3 --> stroke_1: (unread writing)
`;

/** The board once a model that can see has read every piece of writing in it (STATE_WORDS). */
export const STATE_MERMAID_READ = `stateDiagram-v2
    direction LR
    state "Idle" as stroke_1
    state "Running" as stroke_2
    state "Paused" as stroke_3
    [*] --> stroke_1
    stroke_1 --> stroke_2: start
    stroke_2 --> stroke_2: tick
    stroke_2 --> stroke_3: pause
    stroke_2 --> [*]: stop
    stroke_3 --> stroke_1: resume
`;
