// The Mermaid the class-diagram boards export as (V1-PLAN §3, §9 D4, A2).
//
// Written by hand from the drawings (fixtures/uml-class.ts), not generated by
// the exporter: this is what `toMermaid` must say, and the one text every hand
// of a board must export. The ids are the marks' own, said in Mermaid as D2
// says them: a class is its box's stroke (`stroke_1`), or — ruled in four
// strokes — its figure (`figure_12_13_14_15`). Classes come in the drawing's
// reading order, then the relations, by the classes they join.
//
// A class is `class <id>["<name>"]`, its members in `{ … }` — attributes, then
// methods. A member is a method only when its words say so (a name and its
// parentheses); so an attribute's parentheses are written as entities, which
// Mermaid decodes, and it never takes one for a method. Writing nobody has
// read is written "(unread writing)" — in a member, as `#40;unread writing#41;`,
// since its words do not say it is a method. A relation is written from the
// class at its marked end: `Parent <|-- Child`, `Whole *-- Part`,
// `Whole o-- Part`, and `From --> To` for an association; a multiplicity is a
// quoted cardinality beside the class it stands at.

/** A2 — two classes with compartments and an inheritance arrow — before anybody has read the writing. */
export const A2_MERMAID_UNREAD = `classDiagram
    class stroke_1["(unread writing)"] {
        #40;unread writing#41;
        #40;unread writing#41;
        #40;unread writing#41;
    }
    class stroke_4["(unread writing)"] {
        #40;unread writing#41;
        #40;unread writing#41;
    }
    stroke_1 <|-- stroke_4
`;

/** A2 once a model that can see has read every piece of writing in it (A2_WORDS). */
export const A2_MERMAID_READ = `classDiagram
    class stroke_1["Animal"] {
        +name: String
        +age: int
        +eat()
    }
    class stroke_4["Dog"] {
        +breed: String
        +bark()
    }
    stroke_1 <|-- stroke_4
`;

/** The bench's board, before anybody has read the writing. */
export const DIAGRAM_MERMAID_UNREAD = `classDiagram
    class stroke_1["(unread writing)"] {
        #40;unread writing#41;
        #40;unread writing#41;
    }
    class stroke_4["(unread writing)"] {
        #40;unread writing#41;
        #40;unread writing#41;
        #40;unread writing#41;
        #40;unread writing#41;
    }
    class stroke_7["(unread writing)"] {
        #40;unread writing#41;
    }
    class stroke_9["(unread writing)"] {
        #40;unread writing#41;
        #40;unread writing#41;
    }
    class figure_12_13_14_15["(unread writing)"] {
        #40;unread writing#41;
    }
    class stroke_17["(unread writing)"]
    stroke_1 "(unread writing)" *-- "(unread writing)" stroke_4
    stroke_4 <|-- stroke_9
    stroke_4 <|-- figure_12_13_14_15
    stroke_7 "(unread writing)" o-- stroke_4
    stroke_9 --> stroke_17
`;

/** The bench's board once its writing is read (DIAGRAM_WORDS). */
export const DIAGRAM_MERMAID_READ = `classDiagram
    class stroke_1["Canvas"] {
        -shapes: Shape#91;#93;
        +draw()
    }
    class stroke_4["Shape"] {
        #35;x: int
        #35;y: int
        +area() double
        +move(dx, dy)
    }
    class stroke_7["Layer"] {
        +visible: bool
    }
    class stroke_9["Circle"] {
        -r: double
        +area() double
    }
    class figure_12_13_14_15["Square"] {
        -side: double
    }
    class stroke_17["Point"]
    stroke_1 "1" *-- "*" stroke_4
    stroke_4 <|-- stroke_9
    stroke_4 <|-- figure_12_13_14_15
    stroke_7 "0..1" o-- stroke_4
    stroke_9 --> stroke_17
`;
