// The Mermaid the ER board exports as (V1-PLAN §3, §9 D6).
//
// Written by hand from the drawing (fixtures/er.ts), not generated by the
// exporter: this is what `toMermaid` must say, and the one text every hand of
// the board must export. The ids are the marks' own, said in Mermaid as D2
// says them: an entity is its box's stroke (`stroke_1`), its name an alias.
// The relationships run across the page, so it says `direction LR`. Entities
// come in reading order — the drawing's columns, left to right, Order above
// Invoice — then the relationships by the entities they join, the first
// standing to the left of the second, each end's cardinality as the words at
// that end say it.
//
// A cardinality is Mermaid's own crow's-foot token: `||` exactly one, `|o` /
// `o|` zero or one, `}o` / `o{` zero or more, `}|` / `|{` one or more, the
// first pair on a line's left side, the second on its right. Writing nobody
// has read says nothing about how many, so it is written as the least it
// claims — zero or more, `}o` and `o{` — and named in the notes. Writing
// nobody has read is written "(unread writing)".

/** The board before anybody has read the writing. */
export const ER_MERMAID_UNREAD = `erDiagram
    direction LR
    stroke_1["(unread writing)"]
    stroke_2["(unread writing)"]
    stroke_3["(unread writing)"]
    stroke_4["(unread writing)"]
    stroke_1 }o--o{ stroke_2 : "(unread writing)"
    stroke_2 }o--o{ stroke_3 : "(unread writing)"
    stroke_2 }o--o{ stroke_4 : "(unread writing)"
`;

/** The board once a model that can see has read every piece of writing in it (ER_WORDS). */
export const ER_MERMAID_READ = `erDiagram
    direction LR
    stroke_1["Customer"]
    stroke_2["Order"]
    stroke_3["Line item"]
    stroke_4["Invoice"]
    stroke_1 ||--o{ stroke_2 : "places"
    stroke_2 ||--|{ stroke_3 : "contains"
    stroke_2 ||--o| stroke_4 : "bills"
`;
