// The Mermaid D1's hand-drawn flowchart exports as (V1-PLAN §3, §9 D2).
//
// Written by hand from the drawing (fixtures/flowchart.ts), not generated by
// the exporter: this is what `toMermaid` must say, and the one text every one
// of the bench's 36 hands must export — its seeds, its steady and shaky hands,
// its box tilted up to ten degrees either way. The ids are the marks' own,
// said in Mermaid: `stroke:1` is `stroke_1`, and a symbol drawn with several
// strokes — the decision in two halves, the box ruled in four — is its figure
// (`figure:stroke:6+stroke:7`), said by its strokes' numbers in order.
//
// Nodes come in the drawing's reading order (rows down the page, each row
// left to right), then the flows, grouped by the node each one leaves. The
// flows run down the page, so the header says TD. Writing nobody has read is
// written as "(unread writing)" — its words are not known, and are never
// invented — and a symbol with no writing in it is written blank.
//
// D3 (Mermaid in) can take these as its inputs: import them, export again,
// and the text must come back.

/** Every hand's flowchart before anybody has read the writing. */
export const FLOWCHART_MERMAID_UNREAD = `flowchart TD
    stroke_1(["(unread writing)"])
    stroke_2[/" "/]
    stroke_3["(unread writing)"]
    stroke_4{"(unread writing)"}
    stroke_5["(unread writing)"]
    figure_6_7{" "}
    stroke_12(((" ")))
    figure_8_9_10_11[" "]
    stroke_1 --> stroke_2
    stroke_2 --> stroke_3
    stroke_3 --> stroke_4
    stroke_4 -->|"(unread writing)"| stroke_5
    stroke_4 -->|"(unread writing)"| figure_6_7
    stroke_5 --> stroke_12
    figure_6_7 --- figure_8_9_10_11
    figure_8_9_10_11 --> stroke_12
`;

/** What a model that can see reads each piece of writing as, by what it labels (the fixture's names). */
export const FLOWCHART_WORDS: Record<string, string> = {
  T1: 'Start',
  P1: 'Read the order',
  Q1: 'In stock?',
  P2: 'Ship it',
  f4: 'yes',
  f5: 'no',
};

/** The same flowchart once a model has read every piece of writing in it. */
export const FLOWCHART_MERMAID_READ = `flowchart TD
    stroke_1(["Start"])
    stroke_2[/" "/]
    stroke_3["Read the order"]
    stroke_4{"In stock?"}
    stroke_5["Ship it"]
    figure_6_7{" "}
    stroke_12(((" ")))
    figure_8_9_10_11[" "]
    stroke_1 --> stroke_2
    stroke_2 --> stroke_3
    stroke_3 --> stroke_4
    stroke_4 -->|"yes"| stroke_5
    stroke_4 -->|"no"| figure_6_7
    stroke_5 --> stroke_12
    figure_6_7 --- figure_8_9_10_11
    figure_8_9_10_11 --> stroke_12
`;
