// The Mermaid the mind-map board exports as (V1-PLAN §3, §9 D6).
//
// Written by hand from the drawing (fixtures/mindmap.ts), not generated by the
// exporter: this is what `toMermaid` must say, and the one text every hand of
// the board must export. The ids are the marks' own, said in Mermaid as D2
// says them: a node is its shape's stroke (`stroke_1`), its words in the
// shape's own delimiters — `((…))` for a circle, `[…]` for a box — every label
// quoted. The tree is what the indentation says: the centre first, then each
// node's branches nested one level in, in the order a hand reads round the
// node they leave — clockwise from the top round the centre: Food (up and
// right), Travel (down and right), Sleep (left); round any other node
// clockwise from the way it faces, away from its parent: Pizza (up) before
// Ramen (down) — so a hand's map and the text agree on which branch comes
// first. Writing nobody has read is written "(unread writing)".

/** The board before anybody has read the writing. */
export const MINDMAP_MERMAID_UNREAD = `mindmap
    stroke_1(("(unread writing)"))
        stroke_2["(unread writing)"]
            stroke_5["(unread writing)"]
            stroke_6["(unread writing)"]
        stroke_3(("(unread writing)"))
        stroke_4["(unread writing)"]
            stroke_7["(unread writing)"]
`;

/** The board once a model that can see has read every piece of writing in it (MINDMAP_WORDS). */
export const MINDMAP_MERMAID_READ = `mindmap
    stroke_1(("Trip"))
        stroke_2["Food"]
            stroke_5["Pizza"]
            stroke_6["Ramen"]
        stroke_3(("Travel"))
        stroke_4["Sleep"]
            stroke_7["Hotel"]
`;
