// The Mermaid the sequence-diagram board exports as (V1-PLAN §3, §9 D5, A3).
//
// Written by hand from the drawing (fixtures/sequence.ts), not generated by
// the exporter: this is what `toMermaid` must say, and the one text every
// hand of the board must export. The ids are the marks' own, said in Mermaid
// as D2 says them: a participant is its box's stroke (`stroke_1`), or its
// figure's head. Participants come left to right, as the drawing stands
// them; then the messages, down the page, in the order they are drawn there
// — never the log's.
//
// A participant is `participant <id> as <name>` (an actor `actor <id> as
// <name>`); a message is `<from><arrow><to>: <label>`, the arrow as its line
// and head say: `->>` a solid line with a head, `-->>` a dashed one, `->` and
// `-->` with no head. A message to its own lifeline is a self-message,
// `<id>->><id>`. Writing nobody has read is written "(unread writing)".

/** A3 — three lifelines and four messages — before anybody has read the writing. */
export const A3_MERMAID_UNREAD = `sequenceDiagram
    participant stroke_1 as (unread writing)
    participant stroke_2 as (unread writing)
    participant stroke_3 as (unread writing)
    stroke_1->>stroke_2: (unread writing)
    stroke_2->>stroke_2: (unread writing)
    stroke_2->>stroke_3: (unread writing)
    stroke_3-->>stroke_1: (unread writing)
`;

/** A3 once a model that can see has read every piece of writing in it (A3_WORDS). */
export const A3_MERMAID_READ = `sequenceDiagram
    participant stroke_1 as Alice
    participant stroke_2 as Bob
    participant stroke_3 as Carol
    stroke_1->>stroke_2: request
    stroke_2->>stroke_2: validate
    stroke_2->>stroke_3: store
    stroke_3-->>stroke_1: done
`;

/** The same board with Alice drawn as a stick figure: an actor. */
export const A3_ACTOR_MERMAID_READ = `sequenceDiagram
    actor stroke_1 as Alice
    participant stroke_2 as Bob
    participant stroke_3 as Carol
    stroke_1->>stroke_2: request
    stroke_2->>stroke_2: validate
    stroke_2->>stroke_3: store
    stroke_3-->>stroke_1: done
`;
